version: '3.8'

services:
  # CockroachDB (single-node)
  cockroach:
    image: cockroachdb/cockroach:v25.1.2
    container_name: cockroach
    hostname: cockroach
    command: start-single-node --insecure --http-addr=cockroach:8080
    ports:
      - "26257:26257"  # SQL порт
      - "8080:8080"    # Admin UI порт
    volumes:
      - cockroach-data:/cockroach/cockroach-data

  # Flyway для миграций
  flyway:
    image: flyway/flyway:11.4.1
    container_name: flyway
    depends_on:
      - cockroach
    volumes:
      - ./cockroachdb/migrations:/flyway/sql
    command: -url=jdbc:postgresql://cockroach:26257/defaultdb?sslmode=disable -user=root -password= -connectRetries=5 migrate

  # Minio (S3 хранилище)
  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data

  gateway:
    container_name: gateway
    build:
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    depends_on:
      - cockroach
      - minio


volumes:
  kafka-data:
  minio-data:
  cockroach-data:
