services:
  # CockroachDB (single-node)
  cockroach:
    image: cockroachdb/cockroach:v25.1.2
    container_name: cockroach
    hostname: cockroach
    command: start-single-node --insecure --http-addr=cockroach:8080
    ports:
      - "26257:26257"  # SQL порт
      - "8080:8080"    # Admin UI порт
    volumes:
      - cockroach-data:/cockroach/cockroach-data

  # Flyway для миграций
  flyway:
    image: flyway/flyway:11.4.1
    container_name: flyway
    depends_on:
      - cockroach
    volumes:
      - ./cockroachdb/migrations:/flyway/sql
    command: -url=jdbc:postgresql://cockroach:26257/defaultdb?sslmode=disable -user=root -password= -connectRetries=5 migrate

  # Minio (S3 хранилище)
  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data

  broker:
    image: apache/kafka:4.0.0
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9092:9092"
      - "9093:9093"

volumes:
  minio-data:
  cockroach-data:
