version: '3.8'

services:
  # CockroachDB (single-node)
  cockroach:
    image: cockroachdb/cockroach:v25.1.2
    container_name: cockroach
    hostname: cockroach
    command: start-single-node --insecure --http-addr=cockroach:8080
    ports:
      - "26257:26257"  # SQL порт
      - "8080:8080"    # Admin UI порт
    volumes:
      - cockroach-data:/cockroach/cockroach-data

  # Kafka (single broker)
  broker:
    image: apache/kafka:4.0.0
    container_name: kafka
    restart: always
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data

  # Flyway для миграций
  flyway:
    image: flyway/flyway:11.4.1
    container_name: flyway
    depends_on:
      - cockroach
    volumes:
      - ./cockroachdb/migrations:/flyway/sql
    command: -url=jdbc:postgresql://cockroach:26257/defaultdb?sslmode=disable -user=root -password= -connectRetries=5 migrate

volumes:
  cockroach-data:
  kafka-data:
