-- +goose Up
-- Хранит статистику по постам в разных платформах
CREATE TABLE IF NOT EXISTS post_platform_stats_history (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id INT NOT NULL,
    FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE CASCADE,
    post_union_id INT NOT NULL,
    FOREIGN KEY (post_union_id) REFERENCES post_union (id) ON DELETE CASCADE,
    platform STRING(32) NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), -- Время записи статистики
    views INT NOT NULL DEFAULT 0,
    reactions INT NOT NULL DEFAULT 0,
    INDEX idx_post_platform_recorded (post_union_id, platform, recorded_at)
);

-- Таблица задач для обновления статистики
CREATE TABLE IF NOT EXISTS stats_update_tasks (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_union_id INT NOT NULL,
    FOREIGN KEY (post_union_id) REFERENCES post_union (id) ON DELETE CASCADE,
    platform STRING(32) NOT NULL,
    next_update_at TIMESTAMPTZ NOT NULL,
    last_updated_at TIMESTAMPTZ,
    update_interval_minutes INT NOT NULL DEFAULT 10, -- Интервал обновления в минутах
    is_locked BOOL NOT NULL DEFAULT FALSE,
    locked_at TIMESTAMPTZ,
    locked_by STRING(255), -- Идентификатор воркера/реплики
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    INDEX idx_next_update (next_update_at),
    INDEX idx_post_platform (post_union_id, platform),
    UNIQUE (post_union_id, platform)
);
