-- Пользователь
CREATE TABLE IF NOT EXISTS "user" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    secret STRING(64) NOT NULL DEFAULT gen_random_uuid()
);

-- ВКонтакте как канал для постов
CREATE TABLE IF NOT EXISTS channel_vk (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE,
    group_id INT NOT NULL,
    api_key STRING(128) NOT NULL,
    last_updated_timestamp TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_channel_vk_last_updated_timestamp
ON channel_vk (last_updated_timestamp);

/*
Проверять каналы, которые нужно прослушать, можно так:

SELECT id, last_updated_timestamp
FROM channel_vk
WHERE last_updated_timestamp < NOW() - INTERVAL '5 minutes'
FOR UPDATE;
 */

-- Telegram как канал для постов
CREATE TABLE IF NOT EXISTS channel_tg (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE,
    channel_id INT NOT NULL,
    discussion_id INT -- NULL, если канал не имеет обсуждений
);

-- Медиа-файлы
CREATE TABLE IF NOT EXISTS mediafile (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_path STRING(256) NOT NULL,
    file_type STRING(32) NOT NULL, -- photo / video / raw
    uploaded_by_user_id INT NOT NULL,
    FOREIGN KEY (uploaded_by_user_id) REFERENCES "user" (id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Общий пост
CREATE TABLE IF NOT EXISTS post_union (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE,
    text STRING(1024), -- может быть NULL только в том случае, если есть mediafile
    platforms STRING(32)[] NOT NULL DEFAULT '{}', -- vk / tg / etc
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    pub_datetime TIMESTAMP -- запланированное время публикации; если NULL, то публикуется немедленно
);

-- Прикрепление медиа-файла к посту
CREATE TABLE IF NOT EXISTS post_union_mediafile (
    post_union_id INT NOT NULL,
    mediafile_id INT NOT NULL,
    FOREIGN KEY (post_union_id) REFERENCES post_union (id) ON DELETE CASCADE,
    FOREIGN KEY (mediafile_id) REFERENCES mediafile (id) ON DELETE CASCADE,
    PRIMARY KEY (post_union_id, mediafile_id)
);

-- Действие публикации поста
CREATE TABLE IF NOT EXISTS post_action (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_union_id INT NOT NULL,
    FOREIGN KEY (post_union_id) REFERENCES post_union (id),
    platform STRING(32) NOT NULL, -- vk / tg / etc
    status STRING(32) NOT NULL, -- pending / success / error
    error_message STRING(2048),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Пост во ВКонтакте
CREATE TABLE IF NOT EXISTS post_vk (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_union_id INT NOT NULL,
    FOREIGN KEY (post_union_id) REFERENCES post_union (id),
    post_id INT NOT NULL
);

-- Пост в Telegram
CREATE TABLE IF NOT EXISTS post_tg (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_union_id INT NOT NULL,
    FOREIGN KEY (post_union_id) REFERENCES post_union (id),
    post_id INT NOT NULL
);

-- Состояние бота в Telegram
CREATE TABLE IF NOT EXISTS tg_bot_state (
    id INT PRIMARY KEY DEFAULT 1,
    last_update_id INT NOT NULL DEFAULT 0
);

-- Если нет записи для бота, то создаём её
INSERT INTO tg_bot_state (id, last_update_id) VALUES (1, 0) ON CONFLICT DO NOTHING;
