-- обновление таблицы user: добавляем хэш пароля для bcrypt,
-- имя, email
ALTER TABLE "user"
ADD COLUMN IF NOT EXISTS password_hash STRING(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS nickname STRING(255) DEFAULT "",
ADD COLUMN IF NOT EXISTS email STRING(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS vk_id INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS vk_access_token STRING(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS vk_refresh_token STRING(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS vk_token_expires_at TIMESTAMPTZ DEFAULT NULL;
