-- Хранит статистику по постам в разных платформах
CREATE TABLE IF NOT EXISTS post_platform_stats_history (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id INT NOT NULL,
    FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE CASCADE,
    post_union_id INT NOT NULL,
    FOREIGN KEY (post_union_id) REFERENCES post_union (id) ON DELETE CASCADE,
    platform STRING(32) NOT NULL,
    period_start TIMESTAMPTZ NOT NULL,
    period_end TIMESTAMPTZ, -- NULL, если это текущий период
    views INT NOT NULL DEFAULT 0,
    reactions INT NOT NULL DEFAULT 0
);

