-- обновление таблицы user: добавляем хэш пароля для bcrypt,
-- имя, email
ALTER TABLE "user"
ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS nickname VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS email VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS vk_id VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS vk_access_token VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS vk_refresh_token VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS vk_token_expires_at TIMESTAMP DEFAULT NULL;
